---
title: "problemset3_teramoto"
format: html
editor: visual
---

```{r}
pacman::p_load(tidyverse,
               haven,
               here,
               foreign,
               janitor,
               TAM,
               sas7bdat,
               ggplot2,
               writexl,
               HMDHFDplus)
here::i_am("problemset3_teramoto.qmd")
library(here)
here()
setwd("~/Library/CloudStorage/GoogleDrive-erikateramoto@g.ecc.u-tokyo.ac.jp/My Drive/Wisc/Wisc 2025-2026/SOC 756/problem sets/demtech-2")
```

You can add options to executable code like this

```{r}

  df <- read_table("data/bltper_1x1.txt",
                   skip = 1)|>
    filter(Year == 2005)|>
    filter(Age %in% 16:31)|>
    select(year = Year,
           age = Age,
           nqx_die = qx)|>
    mutate(
      age = as.numeric(age),
      age = case_when(is.na(age) ~ 110,
                   TRUE ~ age),
      #q_die = (2*nMx)/(2+nMx),
      #q_die2 = nMx/(1+(1-ax)*nMx),
      q_acc = pmax(0,0.062 - (0.000053*age^2)),
      q_all = nqx_die + q_acc,
      p_all = 1-q_all,
      lx =  c(85000, 85000 * cumprod(p_all))[1:length(p_all)],
      ndx_die = lx*nqx_die,
      ndx_acc = lx*q_acc)

  write_xlsx(df,
          path = here::here("tables","ps3_2.xlsx"))  
```

The `echo: false` option disables the printing of code (only output is displayed).
